/* Auto-generated by scripts/typings.mjs — do not edit. */
/* Source: Stablehouse Public (v1-dev) */

export const API_INFO = {
  title: "Stablehouse Public",
  version: "v1-dev",
  operationIds: ["GetDevOnly","GetTag","ValidateTag"],
};

export class ApiClient {
  constructor(baseUrl) {
    this.baseUrl = baseUrl;
  }

  request(method, path) {
    return fetch(new URL(path, this.baseUrl), { method }).then((r) => r.json());
  }

  /** Dev-only endpoint (absent from prod fixture) */
  GetDevOnly() {
    return this.request("GET", "/v1/demo/dev-only");
  }

  /** Get account tag */
  GetTag() {
    return this.request("GET", "/v1/account/tag/get");
  }

  /** Validate tag format and existence */
  ValidateTag() {
    return this.request("POST", "/v1/account/tag/validate");
  }
}

/** Schema: AccountTag */
export const AccountTagFields = [
  "tag",
  // @deprecated
  "legacyField"
];
